



# import os
# from jira_integration.jira_client import get_jira
# from dotenv import load_dotenv

# def create_jira_stories(stories):
#     load_dotenv()
#     jira = get_jira()

#     project_key = os.getenv("JIRA_PROJECT_KEY")

#     epic_map = {}      # epic_name -> epic_key
#     created_issues = []

#     # 1️⃣ Create Epics
#     for story in stories:
#         epic_name = story["epic_name"]

#         if epic_name not in epic_map:
#             epic = jira.create_issue(
#                 project={"key": project_key},
#                 summary=epic_name,
#                 description=f"Epic generated by AI: {epic_name}",
#                 issuetype={"name": "Epic"}
#             )
#             epic_map[epic_name] = epic.key

#     # 2️⃣ Create Stories under Epics (CORRECT way)
#     for story in stories:
#         epic_key = epic_map[story["epic_name"]]

#         description = f"""{story['description']}

# Acceptance Criteria:
# - """ + "\n- ".join(story.get("acceptance_criteria", [])) + """

# Definition of Done:
# - """ + "\n- ".join(story.get("definition_of_done", []))

#         issue = jira.create_issue(
#             project={"key": project_key},
#             summary=story["summary"],
#             description=description,
#             issuetype={"name": "Task"},     # ✅ correct
#             parent={"key": epic_key}         # ✅ correct for your Jira
#         )

#         created_issues.append(issue.key)

#     return created_issues

from __future__ import annotations

from jira_integration.jira_client import get_jira, get_current_jira_config


def create_jira_stories(stories: list[dict]) -> list[str]:
    jira = get_jira()
    config = get_current_jira_config()
    project_key = config.get("jira_project_key")
    if not project_key:
        raise ValueError("Jira project key is not configured")

    epic_map: dict[str, str] = {}
    created_issues: list[str] = []

    for story in stories:
        epic_name = story["epic_name"]
        if epic_name not in epic_map:
            epic = jira.create_issue(
                project={"key": project_key},
                summary=epic_name,
                description=f"Epic generated by AI: {epic_name}",
                issuetype={"name": "Epic"},
            )
            epic_map[epic_name] = epic.key

    for story in stories:
        epic_key = epic_map[story["epic_name"]]
        description = f"""{story['description']}

Acceptance Criteria:
- """ + "\n- ".join(story.get("acceptance_criteria", [])) + """

Definition of Done:
- """ + "\n- ".join(story.get("definition_of_done", []))

        issue = jira.create_issue(
            project={"key": project_key},
            summary=story["summary"],
            description=description,
            issuetype={"name": "Task"},
            parent={"key": epic_key},
        )
        created_issues.append(issue.key)

    return created_issues