# # from jira_integration.jira_client import get_jira
# # from app.config import JIRA_PROJECT_KEY

# # def create_jira_stories(text):
# #     jira = get_jira()

# #     issue = jira.create_issue(
# #         project=JIRA_PROJECT_KEY,
# #         summary="AI Generated Requirement",
# #         description=text,
# #         issuetype={"name": "Task"}  # ✅ FIX
# #     )

# #     print("Created Jira issue:", issue.key)

# # from jira_integration.jira_client import get_jira
# # from app.config import JIRA_PROJECT_KEY

# # def create_jira_stories(text):
# #     jira = get_jira()

# #     issue = jira.create_issue(
# #         project=JIRA_PROJECT_KEY,
# #         summary="AI Generated Requirement",
# #         description=text,
# #         issuetype={"name": "Task"}
# #     )

# #     print("✅ Created Jira issue:", issue.key)
# #     return issue.key

# from jira import JIRA
# import os
# from dotenv import load_dotenv

# load_dotenv()

# def create_jira_stories(stories):
#     jira = get_jira()
#     created_keys = []

#     for story in stories:
#         description = f"""
# {story['description']}

# Acceptance Criteria:
# - """ + "\n- ".join(story["acceptance_criteria"]) + """

# Definition of Done:
# - """ + "\n- ".join(story["definition_of_done"])

#         issue = jira.create_issue(
#             project={"key": JIRA_PROJECT_KEY},
#             summary=story["summary"],
#             description=description,
#             issuetype={"name": "Task"}
#         )

#         created_keys.append(issue.key)

#     return created_keys


#working currently
# import os
# from jira_integration.jira_client import get_jira
# from dotenv import load_dotenv

# def create_jira_stories(stories):
#     load_dotenv()
#     jira = get_jira()
#     created = []

#     for s in stories:
#         description = f"""
# {s['description']}

# Acceptance Criteria:
# - """ + "\n- ".join(s["acceptance_criteria"]) + """

# Definition of Done:
# - """ + "\n- ".join(s["definition_of_done"])

#         issue = jira.create_issue(
#             project={"key": os.getenv("JIRA_PROJECT_KEY")},
#             summary=s["summary"],
#             description=description,
#             issuetype={"name": "Task"}
#         )

#         created.append(issue.key)

#     return created



import os
from jira_integration.jira_client import get_jira
from dotenv import load_dotenv

def create_jira_stories(stories):
    load_dotenv()
    jira = get_jira()

    project_key = os.getenv("JIRA_PROJECT_KEY")

    epic_map = {}      # epic_name -> epic_key
    created_issues = []

    # 1️⃣ Create Epics
    for story in stories:
        epic_name = story["epic_name"]

        if epic_name not in epic_map:
            epic = jira.create_issue(
                project={"key": project_key},
                summary=epic_name,
                description=f"Epic generated by AI: {epic_name}",
                issuetype={"name": "Epic"}
            )
            epic_map[epic_name] = epic.key

    # 2️⃣ Create Stories under Epics (CORRECT way)
    for story in stories:
        epic_key = epic_map[story["epic_name"]]

        description = f"""{story['description']}

Acceptance Criteria:
- """ + "\n- ".join(story.get("acceptance_criteria", [])) + """

Definition of Done:
- """ + "\n- ".join(story.get("definition_of_done", []))

        issue = jira.create_issue(
            project={"key": project_key},
            summary=story["summary"],
            description=description,
            issuetype={"name": "Task"},     # ✅ correct
            parent={"key": epic_key}         # ✅ correct for your Jira
        )

        created_issues.append(issue.key)

    return created_issues

